### Signup
POST http://localhost:8000/users/register
Content-Type: application/json

{
  "firstName": "zakaria",
  "lastName": "hamdan",
  "email": "zak@test.com",
  "password": "1234"
}

###

### Login
POST http://localhost:8000/users/login
Content-Type: application/json

{
  "email": "zak@test.com",
  "password": "1234"
}

###

### Logout
GET http://localhost:8000/users/logout
Content-Type: application/json

###

### Get My Data
GET http://localhost:8000/users/me
Content-Type: application/json
